version: "2"

services:
  cidb:
    container_name: cidb
    image: mysql
    ports:
      - "13306:3306"
    volumes:
      - ./my-project/cidbdata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: ci_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: 456

  ciapp:
    container_name: ciapp
    image: docker.io/bitnami/codeigniter:4
    ports:
      - "8000:8000"
    links:
      - cidb
    volumes:
      - "./my-project:/app"
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - CODEIGNITER_DATABASE_HOST=cidb
      - CODEIGNITER_DATABASE_PORT_NUMBER=13306
      - CODEIGNITER_DATABASE_USER=db_user
      - CODEIGNITER_DATABASE_PASSWORD=456
      - CODEIGNITER_DATABASE_NAME=ci_db
    depends_on:
      - cidb

  ciphpmyadmin:
    container_name: cipma
    image: phpmyadmin
    ports:
      - 8081:80
    links:
      - cidb
    restart: always
    environment:
      PMA_ARBITRARY: 1
    depends_on:
      - cidb
